export interface Track {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: number;
  duration: number;
  videoId: string;
}

export interface Playlist {
  id: string;
  name: string;
  icon: string;
  description: string;
  time: string;
  tracks: Track[];
}

export const playlists: Playlist[] = [
  {
    id: "subah-ka-sukoon",
    name: "SUBAH KA SUKOON",
    icon: "🌅",
    description: "Fresh, energetic, morning vibes.",
    time: "7 AM – 12 PM",
    tracks: [
      { id: "sksu-1", title: "Khaabon Ke Parinday", artist: "Alyssa Mendonsa, Mohit Chauhan", film: "Zindagi Na Milegi Dobara", year: 2011, duration: 295, videoId: "xZAXVM1rSbk" },
      { id: "sksu-2", title: "Ilahi", artist: "Arijit Singh", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 222, videoId: "4ehgyK5dQfE" },
      { id: "sksu-3", title: "Love You Zindagi", artist: "Jasleen Royal", film: "Dear Zindagi", year: 2016, duration: 248, videoId: "rwn0Zs7ELzc" },
      { id: "sksu-4", title: "Safarnama", artist: "Lucky Ali", film: "Tamasha", year: 2015, duration: 288, videoId: "sOhESxhibAM" },
      { id: "sksu-5", title: "Aashiyan", artist: "Shreya Ghoshal, Nikhil Paul George", film: "Barfi!", year: 2012, duration: 253, videoId: "OuNGySNJjWg" },
      { id: "sksu-6", title: "Patakha Guddi", artist: "Nooran Sisters", film: "Highway", year: 2014, duration: 307, videoId: "rwZDGFuA0xE" },
      { id: "new-subah-ka-sukoon-0", title: "Subhanallah", artist: "Sreerama Chandra, Shilpa Rao", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 249, videoId: "QYO6AlxiRE4" },
      { id: "new-subah-ka-sukoon-1", title: "Sooraj Dooba Hain", artist: "Arijit Singh, Aditi Singh Sharma", film: "Roy", year: 2015, duration: 264, videoId: "nJZcbidTutE" },
      { id: "new-subah-ka-sukoon-2", title: "Badtameez Dil", artist: "Benny Dayal", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 252, videoId: "II2EO3Nw4m0" },
      { id: "new-subah-ka-sukoon-3", title: "Koi Kahe Kehta Rahe", artist: "Shankar Mahadevan, Shaan, KK", film: "Dil Chahta Hai", year: 2001, duration: 346, videoId: "ctJI7pCbxAo" },
      { id: "new-subah-ka-sukoon-4", title: "Dil Chahta Hai", artist: "Shankar Mahadevan", film: "Dil Chahta Hai", year: 2001, duration: 311, videoId: "HoDgYV1NzAI" },
      { id: "new-subah-ka-sukoon-5", title: "Dil Dhadakne Do", artist: "Joi Barua, Suraj Jagan", film: "Zindagi Na Milegi Dobara", year: 2011, duration: 231, videoId: "PyTaSNvflM0" },
      { id: "new-subah-ka-sukoon-6", title: "Suhana Safar", artist: "Mukesh", film: "Madhumati", year: 1958, duration: 220, videoId: "iJu8rb1WL-g" },
      { id: "new-subah-ka-sukoon-7", title: "Zindagi Ek Safar", artist: "Kishore Kumar", film: "Andaz", year: 1971, duration: 258, videoId: "LlvoY4v5zm0" },
      { id: "new-subah-ka-sukoon-8", title: "Matargasti", artist: "Mohit Chauhan", film: "Tamasha", year: 2015, duration: 328, videoId: "TpMSsbzvRe4" },
      { id: "new-subah-ka-sukoon-9", title: "Wake Up Sid!", artist: "Shankar Mahadevan", film: "Wake Up Sid", year: 2009, duration: 231, videoId: "Jqzz8K6mMVs" },
      { id: "new-subah-ka-sukoon-10", title: "Mahi Ve", artist: "A.R. Rahman", film: "Highway", year: 2014, duration: 240, videoId: "S1aQhVUy_9g" },
      { id: "new-subah-ka-sukoon-11", title: "Der Lagi Lekin", artist: "Shankar Mahadevan", film: "Zindagi Na Milegi Dobara", year: 2011, duration: 357, videoId: "2apfulo5uqc" },
      { id: "new-subah-ka-sukoon-12", title: "Illahi (Reprise)", artist: "Mohit Chauhan", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 213, videoId: "ZZ-4t3xGNnQ" },
      { id: "new-subah-ka-sukoon-13", title: "Senorita", artist: "Farhan Akhtar, Hrithik Roshan, Abhay Deol", film: "Zindagi Na Milegi Dobara", year: 2011, duration: 231, videoId: "2Z0Put0teCM" },
      { id: "new2-subah-ka-sukoon-0", title: "Zaalima", artist: "Arijit Singh", film: "Raees", year: 2017, duration: 299, videoId: "hhdSyBHuI88" },
      { id: "new2-subah-ka-sukoon-1", title: "Bulleya", artist: "Amit Mishra", film: "Ae Dil Hai Mushkil", year: 2016, duration: 349, videoId: "vrqFJ-yjkRw" },
      { id: "new2-subah-ka-sukoon-2", title: "Kaise Hua", artist: "Vishal Mishra", film: "Kabir Singh", year: 2019, duration: 234, videoId: "WWXm39leYew" },
      { id: "new2-subah-ka-sukoon-3", title: "Sun Saathiya", artist: "Priya Saraiya", film: "ABCD 2", year: 2015, duration: 220, videoId: "_NWaYjsz3qY" },
      { id: "new2-subah-ka-sukoon-4", title: "Gerua", artist: "Arijit Singh", film: "Dilwale", year: 2015, duration: 345, videoId: "AEIVhBS6baE" },
      { id: "new2-subah-ka-sukoon-5", title: "Pehli Dafa", artist: "Atif Aslam", film: "", year: 2016, duration: 293, videoId: "NLa4KbumdAY" },
      { id: "new2-subah-ka-sukoon-6", title: "Soch Na Sake", artist: "Arijit Singh", film: "Airlift", year: 2016, duration: 280, videoId: "skPuv-EppEg" },
      { id: "new2-subah-ka-sukoon-7", title: "Sab Tera", artist: "Armaan Malik", film: "Baaghi", year: 2016, duration: 228, videoId: "sZfnwayum2M" },
      { id: "new2-subah-ka-sukoon-8", title: "Sanam Re", artist: "Arijit Singh", film: "Sanam Re", year: 2016, duration: 308, videoId: "utU4laPPKls" },
      { id: "new2-subah-ka-sukoon-9", title: "Main Tera Boyfriend", artist: "Arijit Singh", film: "Raabta", year: 2017, duration: 276, videoId: "FQS7i2z1CoA" },
    ],
  },
  {
    id: "dopahar-ki-dhoop",
    name: "DOPAHAR KI DHOOP",
    icon: "☕",
    description: "Lazy afternoon, mellow, acoustic.",
    time: "12 PM – 4 PM",
    tracks: [
      { id: "dkd-1", title: "Phir Se Ud Chala", artist: "Mohit Chauhan", film: "Rockstar", year: 2011, duration: 283, videoId: "-3gQ6HIkRys" },
      { id: "dkd-2", title: "Kyon", artist: "Papon, Sunidhi Chauhan", film: "Barfi!", year: 2012, duration: 230, videoId: "aQHled_gLxU" },
      { id: "dkd-3", title: "Yun Hi Chala Chal", artist: "Udit Narayan, Hariharan", film: "Swades", year: 2004, duration: 367, videoId: "fXi5ThNAM0w" },
      { id: "dkd-4", title: "Aao Milo Chalo", artist: "Shaan", film: "Jab We Met", year: 2007, duration: 280, videoId: "u7hfwX81bY4" },
      { id: "dkd-5", title: "Iktara", artist: "Kavita Seth", film: "Wake Up Sid", year: 2009, duration: 234, videoId: "ZlOZktsODpA" },
      { id: "new-dopahar-ki-dhoop-0", title: "Te Amo", artist: "Ash King, Sunidhi Chauhan", film: "Dum Maaro Dum", year: 2011, duration: 287, videoId: "qNnIoaL5HrE" },
      { id: "new-dopahar-ki-dhoop-1", title: "Saibo", artist: "Shreya Ghoshal, Tochi Raina", film: "Shor in the City", year: 2011, duration: 196, videoId: "9Bmh6vaQt0s" },
      { id: "new-dopahar-ki-dhoop-2", title: "O Gujariya", artist: "Evangeline", film: "Queen", year: 2014, duration: 272, videoId: "77b2teUO1Bg" },
      { id: "new-dopahar-ki-dhoop-3", title: "Sham", artist: "Amit Trivedi, Neuman Pinto", film: "Aisha", year: 2010, duration: 265, videoId: "kl8T6tsOZJk" },
      { id: "new-dopahar-ki-dhoop-4", title: "In Dino", artist: "Soham", film: "Life in a Metro", year: 2007, duration: 340, videoId: "P7JyrhGnjhg" },
      { id: "new-dopahar-ki-dhoop-5", title: "Teri Jhuki Nazar", artist: "Shafqat Amanat Ali", film: "Murder 3", year: 2013, duration: 278, videoId: "jQTSk-12POI" },
      { id: "new-dopahar-ki-dhoop-6", title: "Monta Re", artist: "Swanand Kirkire, Amitabh Bhattacharya", film: "Lootera", year: 2013, duration: 238, videoId: "K6cjoEGIqqs" },
      { id: "new-dopahar-ki-dhoop-7", title: "Banjara", artist: "Mohd. Irfan", film: "Ek Villain", year: 2014, duration: 336, videoId: "HuZ9YtVgadg" },
      { id: "new-dopahar-ki-dhoop-8", title: "Sawaar Loon", artist: "Monali Thakur", film: "Lootera", year: 2013, duration: 256, videoId: "W4rSh7R-KP8" },
      { id: "new-dopahar-ki-dhoop-9", title: "Pee Loon", artist: "Mohit Chauhan", film: "Once Upon A Time In Mumbaai", year: 2010, duration: 285, videoId: "Nbr_KJT0TIc" },
      { id: "new-dopahar-ki-dhoop-10", title: "O Meri Jaan", artist: "KK", film: "Life in a Metro", year: 2007, duration: 298, videoId: "jZi8TI050ec" },
      { id: "new-dopahar-ki-dhoop-11", title: "Gubbare", artist: "Amit Trivedi, Shilpa Rao", film: "Ek Main Aur Ekk Tu", year: 2012, duration: 266, videoId: "pOsa_pTV7Co" },
      { id: "new-dopahar-ki-dhoop-12", title: "Khuda Jaane", artist: "KK, Shilpa Rao", film: "Bachna Ae Haseeno", year: 2008, duration: 333, videoId: "5e25BAAjoY4" },
      { id: "new-dopahar-ki-dhoop-13", title: "Behka", artist: "Karthik", film: "Ghajini", year: 2008, duration: 313, videoId: "y1JeQRA78Uc" },
      { id: "new-dopahar-ki-dhoop-14", title: "Tum Mile", artist: "Neeraj Shridhar", film: "Tum Mile", year: 2009, duration: 344, videoId: "odVptmgIcD0" },
      { id: "new2-dopahar-ki-dhoop-0", title: "Sweety Tera Drama", artist: "Dev Negi", film: "Bareilly Ki Barfi", year: 2017, duration: 147, videoId: "RpuhD_xKadk" },
      { id: "new2-dopahar-ki-dhoop-1", title: "Humsafar", artist: "Akhil Sachdeva", film: "Badrinath Ki Dulhania", year: 2017, duration: 268, videoId: "vIUp4CzOrpQ" },
      { id: "new2-dopahar-ki-dhoop-2", title: "Nazm Nazm", artist: "Arko", film: "Bareilly Ki Barfi", year: 2017, duration: 227, videoId: "-JD8B4Gf4Sc" },
      { id: "new2-dopahar-ki-dhoop-3", title: "Dil Diyan Gallan", artist: "Atif Aslam", film: "Tiger Zinda Hai", year: 2017, duration: 260, videoId: "mevO4I0f5lg" },
      { id: "new2-dopahar-ki-dhoop-4", title: "Tere Mere", artist: "Armaan Malik", film: "Chef", year: 2017, duration: 344, videoId: "vqJRytxAjog" },
      { id: "new2-dopahar-ki-dhoop-5", title: "Hawa Banke", artist: "Darshan Raval", film: "", year: 2019, duration: 196, videoId: "0WAKIz9glCY" },
      { id: "new2-dopahar-ki-dhoop-6", title: "Duniyaa", artist: "Akhil", film: "Luka Chuppi", year: 2019, duration: 222, videoId: "nLPWWgi44-E" },
      { id: "new2-dopahar-ki-dhoop-7", title: "Ban Ja Rani", artist: "Guru Randhawa", film: "Tumhari Sulu", year: 2017, duration: 225, videoId: "hlvbDjksdCg" },
      { id: "new2-dopahar-ki-dhoop-8", title: "Vaaste", artist: "Dhvani Bhanushali", film: "", year: 2019, duration: 196, videoId: "fwcmY5sdXp4" },
      { id: "new2-dopahar-ki-dhoop-9", title: "Leja Re", artist: "Dhvani Bhanushali", film: "", year: 2018, duration: 205, videoId: "-xCw7ruotUg" },
    ],
  },
  {
    id: "chai-aur-chill",
    name: "CHAI AUR CHILL",
    icon: "🌇",
    description: "Relaxing evening transitions.",
    time: "4 PM – 6 PM",
    tracks: [
      { id: "cac-1", title: "Shaam", artist: "Amit Trivedi, Neuman Pinto", film: "Aisha", year: 2010, duration: 265, videoId: "v_hJOCzvABU" },
      { id: "cac-2", title: "Tum Se Hi", artist: "Mohit Chauhan", film: "Jab We Met", year: 2007, duration: 325, videoId: "01HR1uP4kic" },
      { id: "cac-3", title: "Kahin To Hogi Woh", artist: "Rashid Ali, Vasundhara Das", film: "Jaane Tu Ya Jaane Na", year: 2008, duration: 310, videoId: "QGinK1vaK5M" },
      { id: "cac-4", title: "Tu Bin Bataye", artist: "Madhushree, Naresh Iyer", film: "Rang De Basanti", year: 2006, duration: 335, videoId: "jI7FFN4wW5E" },
      { id: "cac-5", title: "Dooba Dooba", artist: "Mohit Chauhan", film: "Silk Route", year: 1998, duration: 282, videoId: "ecPMVO7JuTo" },
      { id: "new-chai-aur-chill-0", title: "Chupke Se", artist: "Sadhana Sargam", film: "Saathiya", year: 2002, duration: 314, videoId: "JLXfTmF9DSI" },
      { id: "new-chai-aur-chill-1", title: "Zehnaseeb", artist: "Chinmayi Sripaada, Shekhar Ravjiani", film: "Hasee Toh Phasee", year: 2014, duration: 215, videoId: "WnU0lH6C0EA" },
      { id: "new-chai-aur-chill-2", title: "Hawayein", artist: "Arijit Singh", film: "Jab Harry Met Sejal", year: 2017, duration: 290, videoId: "cYOB941gyXI" },
      { id: "new-chai-aur-chill-3", title: "Safar", artist: "Arijit Singh", film: "Jab Harry Met Sejal", year: 2017, duration: 268, videoId: "fB13hzTnsBk" },
      { id: "new-chai-aur-chill-4", title: "Mitwa", artist: "Shafqat Amanat Ali, Shankar Mahadevan", film: "Kabhi Alvida Naa Kehna", year: 2006, duration: 382, videoId: "ru_5PA8cwkE" },
      { id: "new-chai-aur-chill-5", title: "Ishq Bulaava", artist: "Sanam Puri, Shipra Goyal", film: "Hasee Toh Phasee", year: 2014, duration: 255, videoId: "c2gSzYLJ8sY" },
      { id: "new-chai-aur-chill-6", title: "Tu Hi Re", artist: "Hariharan, Kavita Krishnamurthy", film: "Bombay", year: 1995, duration: 431, videoId: "V9mN0qBgEzQ" },
      { id: "new-chai-aur-chill-7", title: "Dilko Tumse Pyar Hua", artist: "Roop Kumar Rathod", film: "Rehnaa Hai Terre Dil Mein", year: 2001, duration: 331, videoId: "ED8DrK88ODs" },
      { id: "new-chai-aur-chill-8", title: "Tere Mast Mast Do Nain", artist: "Rahat Fateh Ali Khan", film: "Dabangg", year: 2010, duration: 359, videoId: "Mz2yP0A3t4o" },
      { id: "new-chai-aur-chill-9", title: "Tujh Mein Rab Dikhta Hai", artist: "Roop Kumar Rathod", film: "Rab Ne Bana Di Jodi", year: 2008, duration: 284, videoId: "qoq8B8ThgEM" },
      { id: "new-chai-aur-chill-10", title: "Jashn-E-Bahaaraa", artist: "Javed Ali", film: "Jodhaa Akbar", year: 2008, duration: 315, videoId: "YYq0zm67bH8" },
      { id: "new-chai-aur-chill-11", title: "Yeh Tumhari Meri Baatein", artist: "Dominique Cerejo", film: "Rock On!!", year: 2008, duration: 329, videoId: "pXZFuJKhBKA" },
      { id: "new-chai-aur-chill-12", title: "Tum Ho Toh", artist: "Farhan Akhtar", film: "Rock On!!", year: 2008, duration: 294, videoId: "poYtscS7bto" },
      { id: "new-chai-aur-chill-13", title: "In Lamhon Ke Daaman Mein", artist: "Sonu Nigam, Madhushree", film: "Jodhaa Akbar", year: 2008, duration: 418, videoId: "ve4IQMlTMuY" },
      { id: "new-chai-aur-chill-14", title: "Tere Bina", artist: "A.R. Rahman, Chinmayi", film: "Guru", year: 2007, duration: 309, videoId: "_mwqXnTEHSc" },
      { id: "new2-chai-aur-chill-0", title: "Namo Namo", artist: "Amit Trivedi", film: "Kedarnath", year: 2018, duration: 322, videoId: "yALvgZi-84o" },
      { id: "new2-chai-aur-chill-1", title: "Jaan Nisaar", artist: "Arijit Singh", film: "Kedarnath", year: 2018, duration: 238, videoId: "vdbP_3o73qI" },
      { id: "new2-chai-aur-chill-2", title: "Qaafirana", artist: "Arijit Singh", film: "Kedarnath", year: 2018, duration: 341, videoId: "pKwNDsBxXRA" },
      { id: "new2-chai-aur-chill-3", title: "Mere Naam Tu", artist: "Abhay Jodhpurkar", film: "Zero", year: 2018, duration: 338, videoId: "6vXG7JOYfn8" },
      { id: "new2-chai-aur-chill-4", title: "Sweetheart", artist: "Dev Negi", film: "Kedarnath", year: 2018, duration: 212, videoId: "Fn0gvE6T9ro" },
      { id: "new2-chai-aur-chill-5", title: "Tera Fitoor", artist: "Arijit Singh", film: "Genius", year: 2018, duration: 304, videoId: "TE1GYWKYGkM" },
      { id: "new2-chai-aur-chill-6", title: "Dil Meri Na Sune", artist: "Atif Aslam", film: "Genius", year: 2018, duration: 194, videoId: "JylZrg49aXU" },
      { id: "new2-chai-aur-chill-7", title: "Pal", artist: "Arijit Singh", film: "Jalebi", year: 2018, duration: 246, videoId: "w8LcxY43N5Y" },
      { id: "new2-chai-aur-chill-8", title: "O Saathi", artist: "Atif Aslam", film: "Baaghi 2", year: 2018, duration: 251, videoId: "YuXLN23ZGQo" },
      { id: "new2-chai-aur-chill-9", title: "Lo Safar", artist: "Jubin Nautiyal", film: "Baaghi 2", year: 2018, duration: 282, videoId: "AqtyHzG9Ppc" },
    ],
  },
  {
    id: "shaam-ka-sheher",
    name: "SHAAM KA SHEHER",
    icon: "🌆",
    description: "Warm, nostalgic, driving-home vibe.",
    time: "6 PM – 9 PM",
    tracks: [
      {
        id: "sks-1",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "ZlOZktsODpA",
      },
      {
        id: "sks-2",
        title: "Aao Milo Chalo",
        artist: "Shaan, Ustad Sultan Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 280,
        videoId: "u7hfwX81bY4",
      },
      {
        id: "sks-3",
        title: "Khaabon Ke Parinday",
        artist: "Alyssa Mendonsa, Mohit Chauhan",
        film: "Zindagi Na Milegi Dobara",
        year: 2011,
        duration: 295,
        videoId: "xZAXVM1rSbk",
      },
      {
        id: "sks-4",
        title: "Ilahi",
        artist: "Arijit Singh",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 222,
        videoId: "4ehgyK5dQfE",
      },
      {
        id: "sks-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "sOhESxhibAM",
      },
      {
        id: "sks-6",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "fXi5ThNAM0w",
      },
      {
        id: "sks-7",
        title: "Aaj Kal Zindagi",
        artist: "Shankar Mahadevan",
        film: "Wake Up Sid",
        year: 2009,
        duration: 263,
        videoId: "CV9z9Yarbgk",
      },
      {
        id: "sks-8",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "-3gQ6HIkRys",
      },
      {
        id: "sks-9",
        title: "Kyon",
        artist: "Papon, Sunidhi Chauhan",
        film: "Barfi!",
        year: 2012,
        duration: 230,
        videoId: "aQHled_gLxU",
      },
      {
        id: "sks-10",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "DcULR7rk5Js",
      },
      { id: "new-shaam-ka-sheher-0", title: "Aadat (Deep Blue Version)", artist: "Jal", film: "Kalyug", year: 2005, duration: 334, videoId: "KrgnerBFZp8" },
      { id: "new-shaam-ka-sheher-1", title: "Wo Lamhe Wo Baatein", artist: "Atif Aslam", film: "Zeher", year: 2005, duration: 314, videoId: "-xjhuuVXcF0" },
      { id: "new-shaam-ka-sheher-2", title: "Tu Jaane Na", artist: "Atif Aslam", film: "Ajab Prem Ki Ghazab Kahani", year: 2009, duration: 338, videoId: "EHCG8kno2Lg" },
      { id: "new-shaam-ka-sheher-3", title: "Zara Sa", artist: "KK", film: "Jannat", year: 2008, duration: 303, videoId: "JigspDUOeJQ" },
      { id: "new-shaam-ka-sheher-4", title: "Pehli Nazar Mein", artist: "Atif Aslam", film: "Race", year: 2008, duration: 313, videoId: "BadBAMnPX0I" },
      { id: "new-shaam-ka-sheher-5", title: "Beete Lamhein", artist: "KK", film: "The Train", year: 2007, duration: 315, videoId: "dkTok8ikw_4" },
      { id: "new-shaam-ka-sheher-6", title: "Khuda Jaane", artist: "KK", film: "Bachna Ae Haseeno", year: 2008, duration: 333, videoId: "5e25BAAjoY4" },
      { id: "new-shaam-ka-sheher-7", title: "Haan Tu Hain", artist: "KK", film: "Jannat", year: 2008, duration: 325, videoId: "V1fbOsHBlZE" },
      { id: "new-shaam-ka-sheher-8", title: "Kya Mujhe Pyaar Hai", artist: "KK", film: "Woh Lamhe", year: 2006, duration: 252, videoId: "Gg6NMU4ivXM" },
      { id: "new-shaam-ka-sheher-9", title: "Labon Ko", artist: "KK", film: "Bhool Bhulaiyaa", year: 2007, duration: 344, videoId: "-FP2Cmc7zj4" },
      { id: "new2-shaam-ka-sheher-0", title: "Tujhe Kitna Chahein Aur", artist: "Jubin Nautiyal", film: "Kabir Singh", year: 2019, duration: 274, videoId: "PHUG8lCrTRs" },
      { id: "new2-shaam-ka-sheher-1", title: "Bekhayali", artist: "Sachet Tandon", film: "Kabir Singh", year: 2019, duration: 371, videoId: "VOLKJJvfAbg" },
      { id: "new2-shaam-ka-sheher-2", title: "Tera Ban Jaunga", artist: "Akhil Sachdeva", film: "Kabir Singh", year: 2019, duration: 236, videoId: "Qdz5n1Xe5Qo" },
      { id: "new2-shaam-ka-sheher-3", title: "Ghungroo", artist: "Arijit Singh", film: "War", year: 2019, duration: 302, videoId: "caySD0OJJvk" },
      { id: "new2-shaam-ka-sheher-4", title: "Shaitan Ka Saala", artist: "Vishal Dadlani", film: "Housefull 4", year: 2019, duration: 147, videoId: "oCBDl58lBoU" },
      { id: "new2-shaam-ka-sheher-5", title: "Tum Hi Aana", artist: "Jubin Nautiyal", film: "Marjaavaan", year: 2019, duration: 249, videoId: "1jDkrhxWLUA" },
      { id: "new2-shaam-ka-sheher-6", title: "Kinna Sona", artist: "Jubin Nautiyal", film: "Marjaavaan", year: 2019, duration: 269, videoId: "CDJfnJsXKIw" },
      { id: "new2-shaam-ka-sheher-7", title: "Thodi Jagah", artist: "Arijit Singh", film: "Marjaavaan", year: 2019, duration: 218, videoId: "a9fGonbPW5g" },
      { id: "new2-shaam-ka-sheher-8", title: "Ik Mulaqaat", artist: "Altamash Faridi", film: "Dream Girl", year: 2019, duration: 247, videoId: "kV5fYS_1HaA" },
      { id: "new2-shaam-ka-sheher-9", title: "Pal Pal Dil Ke Paas", artist: "Arijit Singh", film: "Pal Pal Dil Ke Paas", year: 2019, duration: 254, videoId: "lgTHGZF3BQw" },
    ],
  },
  {
    id: "dil-se",
    name: "DIL SE",
    icon: "❤️",
    description: "Romantic, warm, slightly emotional.",
    time: "9 PM – 11 PM",
    tracks: [
      {
        id: "ds-1",
        title: "Pehla Nasha",
        artist: "Udit Narayan, Sadhana Sargam",
        film: "Jo Jeeta Wohi Sikandar",
        year: 1992,
        duration: 310,
        videoId: "ODu7OyAqK-Q",
      },
      {
        id: "ds-2",
        title: "Gulabi Aankhen",
        artist: "Mohammed Rafi",
        film: "The Train",
        year: 1970,
        duration: 268,
        videoId: "Xsn0QjMN3fM",
      },
      {
        id: "ds-3",
        title: "Aankhon Se Tune Kya Keh Diya",
        artist: "Kumar Sanu",
        film: "Ghulam",
        year: 1998,
        duration: 330,
        videoId: "qEFgYftu29c",
      },
      {
        id: "ds-4",
        title: "Dooba Dooba",
        artist: "Mohit Chauhan",
        film: "Silk Route",
        year: 1998,
        duration: 282,
        videoId: "ecPMVO7JuTo",
      },
      {
        id: "ds-5",
        title: "Tu Bin Bataye",
        artist: "Madhushree, Naresh Iyer",
        film: "Rang De Basanti",
        year: 2006,
        duration: 335,
        videoId: "jI7FFN4wW5E",
      },
      {
        id: "ds-6",
        title: "Zara Zara",
        artist: "Bombay Jayashri",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 327,
        videoId: "6CXI5ZQgo7A",
      },
      {
        id: "ds-7",
        title: "Ajab Si",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 253,
        videoId: "cLPkUggsAsE",
      },
      {
        id: "ds-8",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "ZlOZktsODpA",
      },
      {
        id: "ds-9",
        title: "Tum Se Hi",
        artist: "Mohit Chauhan",
        film: "Jab We Met",
        year: 2007,
        duration: 325,
        videoId: "01HR1uP4kic",
      },
      {
        id: "ds-10",
        title: "Kaho Naa Pyaar Hai",
        artist: "Udit Narayan, Alka Yagnik",
        film: "Kaho Naa Pyaar Hai",
        year: 2000,
        duration: 312,
        videoId: "1Nf8eQ9dkGY",
      },
      { id: "new-dil-se-0", title: "Tujhe Dekha Toh", artist: "Kumar Sanu, Lata Mangeshkar", film: "DDLJ", year: 1995, duration: 302, videoId: "cNV5hLSa9H8" },
      { id: "new-dil-se-1", title: "Ek Ladki Ko Dekha", artist: "Kumar Sanu", film: "1942: A Love Story", year: 1994, duration: 276, videoId: "htMvfOfixuM" },
      { id: "new-dil-se-2", title: "Kuch Na Kaho", artist: "Kumar Sanu", film: "1942: A Love Story", year: 1994, duration: 376, videoId: "Kidtrrn4aUM" },
      { id: "new-dil-se-3", title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Kumar Sanu, Alka Yagnik", film: "Saajan", year: 1991, duration: 322, videoId: "RVQsBlI35vw" },
      { id: "new-dil-se-4", title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik", film: "Main Khiladi Tu Anari", year: 1994, duration: 435, videoId: "Yqj1_V90KJo" },
      { id: "new-dil-se-5", title: "Tum Mile Dil Khile", artist: "Kumar Sanu, Alka Yagnik", film: "Criminal", year: 1995, duration: 358, videoId: "nqTS7ngviwQ" },
      { id: "new-dil-se-6", title: "Baazigar O Baazigar", artist: "Kumar Sanu, Alka Yagnik", film: "Baazigar", year: 1993, duration: 450, videoId: "PUO7_Gi6ipg" },
      { id: "new-dil-se-7", title: "Dheere Dheere Se", artist: "Kumar Sanu, Anuradha Paudwal", film: "Aashiqui", year: 1990, duration: 329, videoId: "Mcs2xEZ6K8o" },
      { id: "new-dil-se-8", title: "Tu Pyar Hai Kisi Aur Ka", artist: "Kumar Sanu, Anuradha Paudwal", film: "Dil Hai Ke Manta Nahin", year: 1991, duration: 412, videoId: "DJHwuJZ2uYg" },
      { id: "new-dil-se-9", title: "Adayein Bhi Hain", artist: "Kumar Sanu, Anuradha Paudwal", film: "Dil Hai Ke Manta Nahin", year: 1991, duration: 330, videoId: "MK7a38CM0BA" },
      { id: "new2-dil-se-0", title: "Humraah", artist: "Sachet Tandon", film: "Malang", year: 2020, duration: 299, videoId: "hJBHSmyqv0Y" },
      { id: "new2-dil-se-1", title: "Haan Main Galat", artist: "Arijit Singh", film: "Love Aaj Kal", year: 2020, duration: 218, videoId: "yRB0xbKDebo" },
      { id: "new2-dil-se-2", title: "Aabaad Barbaad", artist: "Arijit Singh", film: "Ludo", year: 2020, duration: 309, videoId: "-ePDTGeB5sw" },
      { id: "new2-dil-se-3", title: "Mehrama", artist: "Darshan Raval", film: "Love Aaj Kal", year: 2020, duration: 249, videoId: "HYUpNJJELeE" },
      { id: "new2-dil-se-4", title: "Chal Ghar Chalen", artist: "Arijit Singh", film: "Malang", year: 2020, duration: 339, videoId: "i_NmPv5WQ0U" },
      { id: "new2-dil-se-5", title: "Malang", artist: "Asees Kaur", film: "Malang", year: 2020, duration: 287, videoId: "mLthx9hSFg8" },
      { id: "new2-dil-se-6", title: "Hardum Humdum", artist: "Arijit Singh", film: "Ludo", year: 2020, duration: 267, videoId: "gwkSOCNs5cw" },
      { id: "new2-dil-se-7", title: "Lut Gaye", artist: "Jubin Nautiyal", film: "", year: 2021, duration: 228, videoId: "xFP4_aqKY8U" },
      { id: "new2-dil-se-8", title: "Taaron Ke Shehar", artist: "Jubin Nautiyal", film: "", year: 2020, duration: 229, videoId: "VAZxSoKb65o" },
      { id: "new2-dil-se-9", title: "BurjKhalifa", artist: "Shashi", film: "Laxmii", year: 2020, duration: 187, videoId: "a0TkeUhcVrM" },
    ],
  },
  {
    id: "raat-abhi-baaki-hai",
    name: "RAAT ABHI BAAKI HAI",
    icon: "🌙",
    description: "Signature late-night playlist.",
    time: "11 PM – 1 AM",
    tracks: [
      {
        id: "rabh-1",
        title: "O Sanam",
        artist: "Lucky Ali",
        film: "",
        year: 1996,
        duration: 306,
        videoId: "qZgTPiuifBo",
      },
      {
        id: "rabh-2",
        title: "Aaoge Jab Tum",
        artist: "Rashid Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 341,
        videoId: "CNZMIhckaA0",
      },
      {
        id: "rabh-3",
        title: "Kahin To Hogi Woh",
        artist: "Rashid Ali, Vasundhara Das",
        film: "Jaane Tu Ya Jaane Na",
        year: 2008,
        duration: 310,
        videoId: "QGinK1vaK5M",
      },
      {
        id: "rabh-4",
        title: "Aankhon Mein Teri",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 310,
        videoId: "8tAxzESfBl4",
      },
      {
        id: "rabh-5",
        title: "Tu Jaane Na",
        artist: "Atif Aslam",
        film: "Ajab Prem Ki Ghazab Kahani",
        year: 2009,
        duration: 310,
        videoId: "P8PWN1OmZOA",
      },
      {
        id: "rabh-6",
        title: "Tere Bina",
        artist: "A.R. Rahman, Chinmayi",
        film: "Guru",
        year: 2007,
        duration: 342,
        videoId: "7HKbt19q3Rc",
      },
      {
        id: "rabh-7",
        title: "Kabira",
        artist: "Tochi Raina, Rekha Bhardwaj",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 260,
        videoId: "jcjOF-MrUs4",
      },
      {
        id: "rabh-8",
        title: "Phir Le Aaya Dil",
        artist: "Arijit Singh",
        film: "Barfi!",
        year: 2012,
        duration: 293,
        videoId: "Z93rAu25KqI",
      },
      {
        id: "rabh-9",
        title: "Shaam",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Aisha",
        year: 2010,
        duration: 265,
        videoId: "v_hJOCzvABU",
      },
      {
        id: "rabh-10",
        title: "Aaj Jaane Ki Zid Na Karo",
        artist: "Farida Khanum",
        film: "",
        year: 1970,
        duration: 427,
        videoId: "C3hOqtRQ9bs",
      },
      { id: "new-raat-abhi-baaki-hai-0", title: "Agar Tum Saath Ho", artist: "Arijit Singh, Alka Yagnik", film: "Tamasha", year: 2015, duration: 341, videoId: "sK7riqg2mr4" },
      { id: "new-raat-abhi-baaki-hai-1", title: "Tum Hi Ho", artist: "Arijit Singh", film: "Aashiqui 2", year: 2013, duration: 262, videoId: "Umqb9KENgmk" },
      { id: "new-raat-abhi-baaki-hai-2", title: "Channa Mereya", artist: "Arijit Singh", film: "Ae Dil Hai Mushkil", year: 2016, duration: 289, videoId: "bzSTpdcs-EI" },
      { id: "new-raat-abhi-baaki-hai-3", title: "Kalank Title Track", artist: "Arijit Singh", film: "Kalank", year: 2019, duration: 311, videoId: "0vZdLWqPoi8" },
      { id: "new-raat-abhi-baaki-hai-4", title: "Tujhe Kitna Chahne Lage", artist: "Arijit Singh", film: "Kabir Singh", year: 2019, duration: 284, videoId: "Hq5OTJdBKQU" },
      { id: "new-raat-abhi-baaki-hai-5", title: "Khairiyat", artist: "Arijit Singh", film: "Chhichhore", year: 2019, duration: 270, videoId: "ugcfBQ_AUYg" },
      { id: "new-raat-abhi-baaki-hai-6", title: "Shayad", artist: "Arijit Singh", film: "Love Aaj Kal", year: 2020, duration: 247, videoId: "iZH_ydGn9i0" },
      { id: "new-raat-abhi-baaki-hai-7", title: "Mast Magan", artist: "Arijit Singh", film: "2 States", year: 2014, duration: 280, videoId: "tmWL-JxUGZc" },
      { id: "new-raat-abhi-baaki-hai-8", title: "Enna Sona", artist: "Arijit Singh", film: "OK Jaanu", year: 2017, duration: 213, videoId: "IZF-rOe9u-g" },
      { id: "new-raat-abhi-baaki-hai-9", title: "Raabta", artist: "Arijit Singh", film: "Agent Vinod", year: 2012, duration: 244, videoId: "zlt38OOqwDc" },
      { id: "new2-raat-abhi-baaki-hai-0", title: "Raataan Lambiyan", artist: "Jubin Nautiyal", film: "Shershaah", year: 2021, duration: 230, videoId: "gvyUuxdRdR4" },
      { id: "new2-raat-abhi-baaki-hai-1", title: "Kabhii Tumhhe", artist: "Darshan Raval", film: "Shershaah", year: 2021, duration: 230, videoId: "Q_CER0JeknA" },
      { id: "new2-raat-abhi-baaki-hai-2", title: "Mann Bharryaa 2.0", artist: "B Praak", film: "Shershaah", year: 2021, duration: 266, videoId: "1poXN3jF3Bw" },
      { id: "new2-raat-abhi-baaki-hai-3", title: "Ranjha", artist: "B Praak", film: "Shershaah", year: 2021, duration: 228, videoId: "V7LwfY5U5WI" },
      { id: "new2-raat-abhi-baaki-hai-4", title: "Chaka Chak", artist: "Shreya Ghoshal", film: "Atrangi Re", year: 2021, duration: 270, videoId: "Vzlq8JFwhb8" },
      { id: "new2-raat-abhi-baaki-hai-5", title: "Rihaayi De", artist: "A.R. Rahman", film: "Mimi", year: 2021, duration: 365, videoId: "5jO9K0rjbt0" },
      { id: "new2-raat-abhi-baaki-hai-6", title: "Rait Zara Si", artist: "Arijit Singh", film: "Atrangi Re", year: 2021, duration: 291, videoId: "XejntCTDZZU" },
      { id: "new2-raat-abhi-baaki-hai-7", title: "Aashiqui Aa Gayi", artist: "Arijit Singh", film: "Radhe Shyam", year: 2021, duration: 259, videoId: "inwnVerWbJo" },
      { id: "new2-raat-abhi-baaki-hai-8", title: "Param Sundari", artist: "Shreya Ghoshal", film: "Mimi", year: 2021, duration: 200, videoId: "UrBbZ2f2H6U" },
      { id: "new2-raat-abhi-baaki-hai-9", title: "Tumse Bhi Zyada", artist: "Arijit Singh", film: "Tadap", year: 2021, duration: 319, videoId: "iwhpS4ow7Zc" },
    ],
  },
  {
    id: "2-baje",
    name: "2 BAJE",
    icon: "🕐",
    description: "For the people who are awake for a reason.",
    time: "1 AM – 3 AM",
    tracks: [
      {
        id: "2b-1",
        title: "Choo Lo",
        artist: "The Local Train",
        film: "",
        year: 2018,
        duration: 304,
        videoId: "sFMRqxCexDk",
      },
      {
        id: "2b-2",
        title: "Aaoge Tum Kabhi",
        artist: "The Local Train",
        film: "",
        year: 2015,
        duration: 317,
        videoId: "hvKaPTmQBA8",
      },
      {
        id: "2b-3",
        title: "Tune Jo Na Kaha",
        artist: "Mohit Chauhan",
        film: "New York",
        year: 2009,
        duration: 303,
        videoId: "01HR1uP4kic",
      },
      {
        id: "2b-4",
        title: "Sach Keh Raha Hai Deewana",
        artist: "KK",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 340,
        videoId: "nya9D8kluE0",
      },
      {
        id: "2b-5",
        title: "Alvida",
        artist: "KK",
        film: "Life In A Metro",
        year: 2007,
        duration: 300,
        videoId: "hM9QDpLHhdw",
      },
      {
        id: "2b-6",
        title: "Tujhe Bhula Diya",
        artist: "Mohit Chauhan, Shekhar, Shruti",
        film: "Anjaana Anjaani",
        year: 2010,
        duration: 326,
        videoId: "NPb9WIzIQsQ",
      },
      {
        id: "2b-7",
        title: "Main Rahoon Ya Na Rahoon",
        artist: "Armaan Malik",
        film: "",
        year: 2015,
        duration: 280,
        videoId: "4WB5y4DAcKE",
      },
      {
        id: "2b-8",
        title: "Phir Mohabbat",
        artist: "Mohd. Irfan, Arijit Singh, Saim",
        film: "Murder 2",
        year: 2011,
        duration: 319,
        videoId: "ZZC9T31knpc",
      },
      {
        id: "2b-9",
        title: "Bhula Dena",
        artist: "Mustafa Zahid",
        film: "Aashiqui 2",
        year: 2013,
        duration: 293,
        videoId: "s0ksvPulHt8",
      },
      {
        id: "2b-10",
        title: "Judaai",
        artist: "Rekha Bhardwaj",
        film: "Badlapur",
        year: 2015,
        duration: 298,
        videoId: "t2VaF0ZX65w",
      },
      { id: "new-2-baje-0", title: "Bol Kaffara Kya Hoga", artist: "Sehar Gul Khan", film: "", year: 2018, duration: 320, videoId: "6CQvJywlECk" },
      { id: "new-2-baje-1", title: "Ghalat Fehmi", artist: "Asim Azhar, Zenab Fatimah Sultan", film: "Superstar", year: 2019, duration: 281, videoId: "_7Aj2adPxHA" },
      { id: "new-2-baje-2", title: "Faasle", artist: "Kaavish", film: "Coke Studio", year: 2017, duration: 348, videoId: "9sekgEXGm-E" },
      { id: "new-2-baje-3", title: "Afreen Afreen", artist: "Rahat Fateh Ali Khan, Momina Mustehsan", film: "Coke Studio", year: 2016, duration: 405, videoId: "kw4tT7SCmaY" },
      { id: "new-2-baje-4", title: "Tajdar-e-Haram", artist: "Atif Aslam", film: "Coke Studio", year: 2015, duration: 612, videoId: "a18py61_F_w" },
      { id: "new-2-baje-5", title: "Tu Kuja Man Kuja", artist: "Shiraz Uppal, Rafaqat Ali Khan", film: "Coke Studio", year: 2016, duration: 465, videoId: "ZQMn5wIoAno" },
      { id: "new-2-baje-6", title: "Tera Woh Pyar", artist: "Momina Mustehsan, Asim Azhar", film: "Coke Studio", year: 2016, duration: 427, videoId: "8367ETnagHo" },
      { id: "new-2-baje-7", title: "Muntazir", artist: "Momina Mustehsan, Danyal Zafar", film: "Coke Studio", year: 2017, duration: 361, videoId: "cs9ORHI8o38" },
      { id: "new-2-baje-8", title: "Aayat", artist: "Arijit Singh", film: "Bajirao Mastani", year: 2015, duration: 262, videoId: "XZ8NF2Yv7J0" },
      { id: "new-2-baje-9", title: "Baaqi", artist: "Arijit Singh", film: "", year: 2021, duration: 230, videoId: "mCcaQ3WAlUQ" },
      { id: "new2-2-baje-0", title: "Kesariya", artist: "Arijit Singh", film: "Brahmastra", year: 2022, duration: 268, videoId: "g6fnFALEseI" },
      { id: "new2-2-baje-1", title: "Apna Bana Le", artist: "Arijit Singh", film: "Bhediya", year: 2022, duration: 261, videoId: "u2NAuswnTKs" },
      { id: "new2-2-baje-2", title: "Rasiya", artist: "Shreya Ghoshal", film: "Brahmastra", year: 2022, duration: 265, videoId: "sAwisCxcLII" },
      { id: "new2-2-baje-3", title: "Manike", artist: "Yohani", film: "Thank God", year: 2022, duration: 197, videoId: "P9Rx8Yvzb64" },
      { id: "new2-2-baje-4", title: "Pasoori", artist: "Shae Gill", film: "Coke Studio", year: 2022, duration: 224, videoId: "5Eqb_-j3FDA" },
      { id: "new2-2-baje-5", title: "Jhoom", artist: "Ali Zafar", film: "", year: 2011, duration: 313, videoId: "tfchHFd3CvU" },
      { id: "new2-2-baje-6", title: "Kahani Suno 2.0", artist: "Kaifi Khalil", film: "", year: 2022, duration: 173, videoId: "_XBVWlI8TsQ" },
      { id: "new2-2-baje-7", title: "Maan Meri Jaan", artist: "King", film: "", year: 2022, duration: 194, videoId: "73vZDNKa_Wg" },
      { id: "new2-2-baje-8", title: "Tu Aake Dekhle", artist: "King", film: "", year: 2020, duration: 269, videoId: "wkNNMCU0fVw" },
      { id: "new2-2-baje-9", title: "Deva Deva", artist: "Arijit Singh", film: "Brahmastra", year: 2022, duration: 279, videoId: "hicTBoq7UbA" },
    ],
  },
  {
    id: "highway-mode",
    name: "HIGHWAY MODE",
    icon: "🚛",
    description: "Truck drivers, night-shift workers, insomniacs.",
    time: "3 AM – 5 AM",
    tracks: [
      {
        id: "hm-1",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "DcULR7rk5Js",
      },
      {
        id: "hm-2",
        title: "Zindagi Ek Safar Hai Suhana",
        artist: "Kishore Kumar",
        film: "Andaz",
        year: 1971,
        duration: 261,
        videoId: "mzxHflxI-es",
      },
      {
        id: "hm-3",
        title: "Khaike Paan Banaraswala",
        artist: "Kishore Kumar",
        film: "Don",
        year: 1978,
        duration: 303,
        videoId: "ZphoNQVYNi0",
      },
      {
        id: "hm-4",
        title: "Neele Neele Ambar Par",
        artist: "Kishore Kumar",
        film: "Kalaakaar",
        year: 1983,
        duration: 287,
        videoId: "ThHYiiZTB1Y",
      },
      {
        id: "hm-5",
        title: "O Mere Dil Ke Chain",
        artist: "Kishore Kumar",
        film: "Mere Jeevan Saathi",
        year: 1972,
        duration: 295,
        videoId: "_w14bUcxl1c",
      },
      {
        id: "hm-6",
        title: "Mere Sapno Ki Rani",
        artist: "Kishore Kumar",
        film: "Aradhana",
        year: 1969,
        duration: 269,
        videoId: "Nw7lcCNSYy8",
      },
      {
        id: "hm-7",
        title: "Pal Pal Dil Ke Paas",
        artist: "Kishore Kumar",
        film: "Blackmail",
        year: 1973,
        duration: 287,
        videoId: "f5dw3nafOuo",
      },
      {
        id: "hm-8",
        title: "Aane Wala Pal",
        artist: "Kishore Kumar",
        film: "Gol Maal",
        year: 1979,
        duration: 298,
        videoId: "VE3SaNOJPGI",
      },
      {
        id: "hm-9",
        title: "Ek Ajnabee Haseena Se",
        artist: "Kishore Kumar",
        film: "Ajnabee",
        year: 1974,
        duration: 276,
        videoId: "vS_JXshiu68",
      },
      {
        id: "hm-10",
        title: "Chookar Mere Man Ko",
        artist: "Kishore Kumar",
        film: "Yaarana",
        year: 1981,
        duration: 337,
        videoId: "LF5Lz9zPfIw",
      },
      { id: "new-highway-mode-0", title: "Dard-E-Disco", artist: "Sukhwinder Singh", film: "Om Shanti Om", year: 2007, duration: 271, videoId: "khlR5jM2ZrI" },
      { id: "new-highway-mode-1", title: "Gallan Goodiyaan", artist: "Yashita Sharma, Manish Kumar Tipu, Farhan Akhtar", film: "Dil Dhadakne Do", year: 2015, duration: 296, videoId: "jCEdTq3j-0U" },
      { id: "new-highway-mode-2", title: "Kar Har Maidaan Fateh", artist: "Sukhwinder Singh, Shreya Ghoshal", film: "Sanju", year: 2018, duration: 311, videoId: "RCgbE6eS-DU" },
      { id: "new-highway-mode-3", title: "London Thumakda", artist: "Labh Janjua, Sonu Kakkar, Neha Kakkar", film: "Queen", year: 2014, duration: 230, videoId: "N5bELC8MXeU" },
      { id: "new-highway-mode-4", title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh, Sapna Awasthi", film: "Dil Se", year: 1998, duration: 414, videoId: "9MX-QejdVaQ" },
      { id: "new-highway-mode-5", title: "Character Dheela", artist: "Neeraj Shridhar, Amrita Kak", film: "Ready", year: 2011, duration: 236, videoId: "xYGMFRpKih4" },
      { id: "new-highway-mode-6", title: "Badtameez Dil", artist: "Benny Dayal", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 252, videoId: "II2EO3Nw4m0" },
      { id: "new-highway-mode-7", title: "Dhinka Chika", artist: "Mika Singh, Amrita Kak", film: "Ready", year: 2011, duration: 272, videoId: "Uzs2BC86t9A" },
      { id: "new-highway-mode-8", title: "Subha Hone Na De", artist: "Mika Singh, Shefali Alvares", film: "Desi Boyz", year: 2011, duration: 288, videoId: "Y7G-tYRzwYY" },
      { id: "new-highway-mode-9", title: "Desi Girl", artist: "Shankar Mahadevan, Sunidhi Chauhan, Vishal Dadlani", film: "Dostana", year: 2008, duration: 306, videoId: "28Zsch1QjPI" },
      { id: "new2-highway-mode-0", title: "Besharam Rang", artist: "Shilpa Rao", film: "Pathaan", year: 2023, duration: 258, videoId: "PkNk4ScHAhM" },
      { id: "new2-highway-mode-1", title: "Jhoome Jo Pathaan", artist: "Arijit Singh", film: "Pathaan", year: 2023, duration: 208, videoId: "pacvj3n-RLw" },
      { id: "new2-highway-mode-2", title: "O Bedardeya", artist: "Arijit Singh", film: "Tu Jhoothi Main Makkaar", year: 2023, duration: 313, videoId: "6Y8SM8F1Ojs" },
      { id: "new2-highway-mode-3", title: "Show Me The Thumka", artist: "Sunidhi Chauhan", film: "Tu Jhoothi Main Makkaar", year: 2023, duration: 236, videoId: "KgpFBdapobY" },
      { id: "new2-highway-mode-4", title: "Tere Pyaar Mein", artist: "Arijit Singh", film: "Tu Jhoothi Main Makkaar", year: 2023, duration: 265, videoId: "WCShpiJ6SLU" },
      { id: "new2-highway-mode-5", title: "Naiyo Lagda", artist: "Kamaal Khan", film: "Kisi Ka Bhai Kisi Ki Jaan", year: 2023, duration: 321, videoId: "lzEop75AeOk" },
      { id: "new2-highway-mode-6", title: "Pyaar Hota Kayi Baar Hai", artist: "Arijit Singh", film: "Tu Jhoothi Main Makkaar", year: 2023, duration: 216, videoId: "HZsRjrYW-lk" },
      { id: "new2-highway-mode-7", title: "Billi Billi", artist: "Sukhbir", film: "Kisi Ka Bhai Kisi Ki Jaan", year: 2023, duration: 194, videoId: "1k7of-Agl3E" },
      { id: "new2-highway-mode-8", title: "Phir Aur Kya Chahiye", artist: "Arijit Singh", film: "Zara Hatke Zara Bachke", year: 2023, duration: 266, videoId: "PR_mFnjFidk" },
      { id: "new2-highway-mode-9", title: "Tere Vaaste", artist: "Varun Jain", film: "Zara Hatke Zara Bachke", year: 2023, duration: 189, videoId: "g5WZLO8BAC8" },
    ],
  },
  {
    id: "subah-hone-wali-hai",
    name: "SUBAH HONE WALI HAI",
    icon: "🌅",
    description: "The emotional transition from night to morning.",
    time: "5 AM – 7 AM",
    tracks: [
      {
        id: "shwh-1",
        title: "Kun Faya Kun",
        artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 469,
        videoId: "T94PHkuydcw",
      },
      {
        id: "shwh-2",
        title: "Arziyan",
        artist: "Javed Ali, Kailash Kher",
        film: "Delhi-6",
        year: 2009,
        duration: 384,
        videoId: "dXdD1_AGBZg",
      },
      {
        id: "shwh-3",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "-3gQ6HIkRys",
      },
      {
        id: "shwh-4",
        title: "Aashiyan",
        artist: "Shreya Ghoshal, Nikhil Paul George",
        film: "Barfi!",
        year: 2012,
        duration: 253,
        videoId: "OuNGySNJjWg",
      },
      {
        id: "shwh-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "sOhESxhibAM",
      },
      {
        id: "shwh-6",
        title: "Patakha Guddi",
        artist: "Nooran Sisters",
        film: "Highway",
        year: 2014,
        duration: 307,
        videoId: "rwZDGFuA0xE",
      },
      {
        id: "shwh-7",
        title: "Zinda",
        artist: "Amit Trivedi",
        film: "Bhaag Milkha Bhaag",
        year: 2013,
        duration: 270,
        videoId: "K9opdAw3Osk",
      },
      {
        id: "shwh-8",
        title: "Aazaadiyan",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Udaan",
        year: 2010,
        duration: 310,
        videoId: "ugm2SOScEqA",
      },
      {
        id: "shwh-9",
        title: "Love You Zindagi",
        artist: "Jasleen Royal",
        film: "Dear Zindagi",
        year: 2016,
        duration: 248,
        videoId: "rwn0Zs7ELzc",
      },
      {
        id: "shwh-10",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "fXi5ThNAM0w",
      },
      { id: "new-subah-hone-wali-hai-0", title: "Kabira (Encore)", artist: "Arijit Singh, Harshdeep Kaur", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 269, videoId: "lwLVJ0E8gN4" },
      { id: "new-subah-hone-wali-hai-1", title: "Main Rang Sharbaton Ka", artist: "Atif Aslam, Chinmayi", film: "Phata Poster Nikhla Hero", year: 2013, duration: 263, videoId: "c-thETScd1g" },
      { id: "new-subah-hone-wali-hai-2", title: "Tere Bin", artist: "Atif Aslam", film: "Bas Ek Pal", year: 2006, duration: 285, videoId: "GmbOGB91CYg" },
      { id: "new-subah-hone-wali-hai-3", title: "Dekhte Dekhte", artist: "Atif Aslam", film: "Batti Gul Meter Chalu", year: 2018, duration: 256, videoId: "rkWJyMhIWLo" },
      { id: "new-subah-hone-wali-hai-4", title: "O Saathi", artist: "Atif Aslam", film: "Baaghi 2", year: 2018, duration: 251, videoId: "YuXLN23ZGQo" },
      { id: "new-subah-hone-wali-hai-5", title: "Dil Diyan Gallan", artist: "Atif Aslam", film: "Tiger Zinda Hai", year: 2017, duration: 260, videoId: "mevO4I0f5lg" },
      { id: "new-subah-hone-wali-hai-6", title: "Tera Hua", artist: "Atif Aslam", film: "Loveyatri", year: 2018, duration: 214, videoId: "eSt0ZCAnukI" },
      { id: "new-subah-hone-wali-hai-7", title: "Paniyon Sa", artist: "Atif Aslam, Tulsi Kumar", film: "Satyameva Jayate", year: 2018, duration: 236, videoId: "Jm7Satp7Zqk" },
      { id: "new-subah-hone-wali-hai-8", title: "Tu Chahiye", artist: "Atif Aslam", film: "Bajrangi Bhaijaan", year: 2015, duration: 272, videoId: "WTLLym2wzIM" },
      { id: "new-subah-hone-wali-hai-9", title: "Samjhawan", artist: "Arijit Singh, Shreya Ghoshal", film: "Humpty Sharma Ki Dulhania", year: 2014, duration: 269, videoId: "H2f7MZaw3Yo" },
      { id: "new2-subah-hone-wali-hai-0", title: "Tum Kya Mile", artist: "Arijit Singh", film: "Rocky Aur Rani Kii Prem Kahaani", year: 2023, duration: 277, videoId: "O9ZtN9C5HMA" },
      { id: "new2-subah-hone-wali-hai-1", title: "Ve Kamleya", artist: "Arijit Singh", film: "Rocky Aur Rani Kii Prem Kahaani", year: 2023, duration: 247, videoId: "QXJyMpxd210" },
      { id: "new2-subah-hone-wali-hai-2", title: "Chaleya", artist: "Arijit Singh", film: "Jawan", year: 2023, duration: 200, videoId: "VAdGW7QDJiU" },
      { id: "new2-subah-hone-wali-hai-3", title: "Heeriye", artist: "Arijit Singh", film: "", year: 2023, duration: 194, videoId: "VlzVXW65-jo" },
      { id: "new2-subah-hone-wali-hai-4", title: "Hua Main", artist: "Raghav Chaitanya", film: "Animal", year: 2023, duration: 277, videoId: "xG6sOnqd7WM" },
      { id: "new2-subah-hone-wali-hai-5", title: "What Jhumka?", artist: "Arijit Singh", film: "Rocky Aur Rani Kii Prem Kahaani", year: 2023, duration: 213, videoId: "P1fIdFRnfqw" },
      { id: "new2-subah-hone-wali-hai-6", title: "Satranga", artist: "Arijit Singh", film: "Animal", year: 2023, duration: 271, videoId: "_Wv2iV8b0hA" },
      { id: "new2-subah-hone-wali-hai-7", title: "Arjan Vailly", artist: "Bhupinder Babbal", film: "Animal", year: 2023, duration: 182, videoId: "zqGW6x_5N0k" },
      { id: "new2-subah-hone-wali-hai-8", title: "Zinda Banda", artist: "Anirudh Ravichander", film: "Jawan", year: 2023, duration: 264, videoId: "stjZKBhQ3lg" },
      { id: "new2-subah-hone-wali-hai-9", title: "Pehle Bhi Main", artist: "Vishal Mishra", film: "Animal", year: 2023, duration: 250, videoId: "QKMTreKTpug" },
    ],
  },
];
