export interface Track {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: number;
  duration: number;
  videoId: string;
}

export interface Playlist {
  id: string;
  name: string;
  icon: string;
  description: string;
  time: string;
  tracks: Track[];
}

export const playlists: Playlist[] = [
  {
    id: "shaam-ka-sheher",
    name: "SHAAM KA SHEHER",
    icon: "🌆",
    description: "Warm, nostalgic, driving-home vibe.",
    time: "6 PM – 9 PM",
    tracks: [
      {
        id: "sks-1",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "Q6T9C8X1l2k",
      },
      {
        id: "sks-2",
        title: "Aao Milo Chalo",
        artist: "Shaan, Ustad Sultan Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 280,
        videoId: "F3v6c7104bA",
      },
      {
        id: "sks-3",
        title: "Khaabon Ke Parinday",
        artist: "Alyssa Mendonsa, Mohit Chauhan",
        film: "Zindagi Na Milegi Dobara",
        year: 2011,
        duration: 295,
        videoId: "cscdqZUdgCk",
      },
      {
        id: "sks-4",
        title: "Ilahi",
        artist: "Arijit Singh",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 222,
        videoId: "87Y5j8y5h70",
      },
      {
        id: "sks-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "OQ-DiP-Cuj4",
      },
      {
        id: "sks-6",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "k5Sg1V1n51E",
      },
      {
        id: "sks-7",
        title: "Aaj Kal Zindagi",
        artist: "Shankar Mahadevan",
        film: "Wake Up Sid",
        year: 2009,
        duration: 263,
        videoId: "qT3K29m7R9c",
      },
      {
        id: "sks-8",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "L02t9e2V37E",
      },
      {
        id: "sks-9",
        title: "Kyon",
        artist: "Papon, Sunidhi Chauhan",
        film: "Barfi!",
        year: 2012,
        duration: 230,
        videoId: "n6Q48Cc07w0",
      },
      {
        id: "sks-10",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "7Vb_lP5t34w",
      },
    ],
  },
  {
    id: "dil-se",
    name: "DIL SE",
    icon: "❤️",
    description: "Romantic, warm, slightly emotional.",
    time: "9 PM – 11 PM",
    tracks: [
      {
        id: "ds-1",
        title: "Pehla Nasha",
        artist: "Udit Narayan, Sadhana Sargam",
        film: "Jo Jeeta Wohi Sikandar",
        year: 1992,
        duration: 310,
        videoId: "w1S2p1-lq6s",
      },
      {
        id: "ds-2",
        title: "Gulabi Aankhen",
        artist: "Mohammed Rafi",
        film: "The Train",
        year: 1970,
        duration: 268,
        videoId: "F5k49D4lZ6c",
      },
      {
        id: "ds-3",
        title: "Aankhon Se Tune Kya Keh Diya",
        artist: "Kumar Sanu",
        film: "Ghulam",
        year: 1998,
        duration: 330,
        videoId: "Ww4t7g9a8sE",
      },
      {
        id: "ds-4",
        title: "Dooba Dooba",
        artist: "Mohit Chauhan",
        film: "Silk Route",
        year: 1998,
        duration: 282,
        videoId: "s3w2yN22H9s",
      },
      {
        id: "ds-5",
        title: "Tu Bin Bataye",
        artist: "Madhushree, Naresh Iyer",
        film: "Rang De Basanti",
        year: 2006,
        duration: 335,
        videoId: "1u4dE-9D3s4",
      },
      {
        id: "ds-6",
        title: "Zara Zara",
        artist: "Bombay Jayashri",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 327,
        videoId: "o-59m6y0r0M",
      },
      {
        id: "ds-7",
        title: "Ajab Si",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 253,
        videoId: "7KKVb0_IdD4",
      },
      {
        id: "ds-8",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "L585-jT-W4Y",
      },
      {
        id: "ds-9",
        title: "Tum Se Hi",
        artist: "Mohit Chauhan",
        film: "Jab We Met",
        year: 2007,
        duration: 325,
        videoId: "Cb6wuzOurPc",
      },
      {
        id: "ds-10",
        title: "Kaho Naa Pyaar Hai",
        artist: "Udit Narayan, Alka Yagnik",
        film: "Kaho Naa Pyaar Hai",
        year: 2000,
        duration: 312,
        videoId: "k2Z4R0t0414",
      },
    ],
  },
  {
    id: "raat-abhi-baaki-hai",
    name: "RAAT ABHI BAAKI HAI",
    icon: "🌙",
    description: "Signature late-night playlist.",
    time: "11 PM – 1 AM",
    tracks: [
      {
        id: "rabh-1",
        title: "O Sanam",
        artist: "Lucky Ali",
        film: "",
        year: 1996,
        duration: 306,
        videoId: "UIy5Bx5qz_4",
      },
      {
        id: "rabh-2",
        title: "Aaoge Jab Tum",
        artist: "Rashid Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 341,
        videoId: "HYGMQ1LRIjI",
      },
      {
        id: "rabh-3",
        title: "Kahin To Hogi Woh",
        artist: "Rashid Ali, Vasundhara Das",
        film: "Jaane Tu Ya Jaane Na",
        year: 2008,
        duration: 310,
        videoId: "y6-M6b90T9c",
      },
      {
        id: "rabh-4",
        title: "Aankhon Mein Teri",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 310,
        videoId: "my6GQzuCsqE",
      },
      {
        id: "rabh-5",
        title: "Tu Jaane Na",
        artist: "Atif Aslam",
        film: "Ajab Prem Ki Ghazab Kahani",
        year: 2009,
        duration: 310,
        videoId: "P3aovt_cCwk",
      },
      {
        id: "rabh-6",
        title: "Tere Bina",
        artist: "A.R. Rahman, Chinmayi",
        film: "Guru",
        year: 2007,
        duration: 342,
        videoId: "A2Wp9v6P-h4",
      },
      {
        id: "rabh-7",
        title: "Kabira",
        artist: "Tochi Raina, Rekha Bhardwaj",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 260,
        videoId: "QYO6AlxiRE4",
      },
      {
        id: "rabh-8",
        title: "Phir Le Aaya Dil",
        artist: "Arijit Singh",
        film: "Barfi!",
        year: 2012,
        duration: 293,
        videoId: "kYJzX62P6x8",
      },
      {
        id: "rabh-9",
        title: "Shaam",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Aisha",
        year: 2010,
        duration: 265,
        videoId: "wX-Y12L-4w8",
      },
      {
        id: "rabh-10",
        title: "Aaj Jaane Ki Zid Na Karo",
        artist: "Farida Khanum",
        film: "",
        year: 1970,
        duration: 427,
        videoId: "Hh2427a9S5A",
      },
    ],
  },
  {
    id: "2-baje",
    name: "2 BAJE",
    icon: "🕐",
    description: "For the people who are awake for a reason.",
    time: "1 AM – 3 AM",
    tracks: [
      {
        id: "2b-1",
        title: "Choo Lo",
        artist: "The Local Train",
        film: "",
        year: 2018,
        duration: 304,
        videoId: "_sT-YpS940bI",
      },
      {
        id: "2b-2",
        title: "Aaoge Tum Kabhi",
        artist: "The Local Train",
        film: "",
        year: 2015,
        duration: 317,
        videoId: "h0H63Z9zY0I",
      },
      {
        id: "2b-3",
        title: "Tune Jo Na Kaha",
        artist: "Mohit Chauhan",
        film: "New York",
        year: 2009,
        duration: 303,
        videoId: "dTu5dTEzVM4",
      },
      {
        id: "2b-4",
        title: "Sach Keh Raha Hai Deewana",
        artist: "KK",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 340,
        videoId: "rj3H9aLw-1E",
      },
      {
        id: "2b-5",
        title: "Alvida",
        artist: "KK",
        film: "Life In A Metro",
        year: 2007,
        duration: 300,
        videoId: "r2yS9b-bC7E",
      },
      {
        id: "2b-6",
        title: "Tujhe Bhula Diya",
        artist: "Mohit Chauhan, Shekhar, Shruti",
        film: "Anjaana Anjaani",
        year: 2010,
        duration: 326,
        videoId: "I28UEa24VPo",
      },
      {
        id: "2b-7",
        title: "Main Rahoon Ya Na Rahoon",
        artist: "Armaan Malik",
        film: "",
        year: 2015,
        duration: 280,
        videoId: "Dp6lbdoprZ0",
      },
      {
        id: "2b-8",
        title: "Phir Mohabbat",
        artist: "Mohd. Irfan, Arijit Singh, Saim",
        film: "Murder 2",
        year: 2011,
        duration: 319,
        videoId: "uVB6rqDMUCc",
      },
      {
        id: "2b-9",
        title: "Bhula Dena",
        artist: "Mustafa Zahid",
        film: "Aashiqui 2",
        year: 2013,
        duration: 293,
        videoId: "REK4qJ4_aC8",
      },
      {
        id: "2b-10",
        title: "Judaai",
        artist: "Rekha Bhardwaj",
        film: "Badlapur",
        year: 2015,
        duration: 298,
        videoId: "g0Q404G72wM",
      },
    ],
  },
  {
    id: "highway-mode",
    name: "HIGHWAY MODE",
    icon: "🚛",
    description: "Truck drivers, night-shift workers, insomniacs.",
    time: "3 AM – 5 AM",
    tracks: [
      {
        id: "hm-1",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "7Vb_lP5t34w",
      },
      {
        id: "hm-2",
        title: "Zindagi Ek Safar Hai Suhana",
        artist: "Kishore Kumar",
        film: "Andaz",
        year: 1971,
        duration: 261,
        videoId: "hE02t2O5V-8",
      },
      {
        id: "hm-3",
        title: "Khaike Paan Banaraswala",
        artist: "Kishore Kumar",
        film: "Don",
        year: 1978,
        duration: 303,
        videoId: "fXw693C0X6k",
      },
      {
        id: "hm-4",
        title: "Neele Neele Ambar Par",
        artist: "Kishore Kumar",
        film: "Kalaakaar",
        year: 1983,
        duration: 287,
        videoId: "N5v9G6m-v0o",
      },
      {
        id: "hm-5",
        title: "O Mere Dil Ke Chain",
        artist: "Kishore Kumar",
        film: "Mere Jeevan Saathi",
        year: 1972,
        duration: 295,
        videoId: "wX-y072v76s",
      },
      {
        id: "hm-6",
        title: "Mere Sapno Ki Rani",
        artist: "Kishore Kumar",
        film: "Aradhana",
        year: 1969,
        duration: 269,
        videoId: "P5y0pY_0v6I",
      },
      {
        id: "hm-7",
        title: "Pal Pal Dil Ke Paas",
        artist: "Kishore Kumar",
        film: "Blackmail",
        year: 1973,
        duration: 287,
        videoId: "v0TejHIZLV8",
      },
      {
        id: "hm-8",
        title: "Aane Wala Pal",
        artist: "Kishore Kumar",
        film: "Gol Maal",
        year: 1979,
        duration: 298,
        videoId: "t7tXh8Gk27Y",
      },
      {
        id: "hm-9",
        title: "Ek Ajnabee Haseena Se",
        artist: "Kishore Kumar",
        film: "Ajnabee",
        year: 1974,
        duration: 276,
        videoId: "fXw693C0X6k",
      },
      {
        id: "hm-10",
        title: "Chookar Mere Man Ko",
        artist: "Kishore Kumar",
        film: "Yaarana",
        year: 1981,
        duration: 337,
        videoId: "v0TejHIZLV8",
      },
    ],
  },
  {
    id: "subah-hone-wali-hai",
    name: "SUBAH HONE WALI HAI",
    icon: "🌅",
    description: "The emotional transition from night to morning.",
    time: "5 AM – 7 AM",
    tracks: [
      {
        id: "shwh-1",
        title: "Kun Faya Kun",
        artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 469,
        videoId: "T9tLZ0J1s9g",
      },
      {
        id: "shwh-2",
        title: "Arziyan",
        artist: "Javed Ali, Kailash Kher",
        film: "Delhi-6",
        year: 2009,
        duration: 384,
        videoId: "kYv9iD03sS0",
      },
      {
        id: "shwh-3",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "L02t9e2V37E",
      },
      {
        id: "shwh-4",
        title: "Aashiyan",
        artist: "Shreya Ghoshal, Nikhil Paul George",
        film: "Barfi!",
        year: 2012,
        duration: 253,
        videoId: "-G51a-u4_tY",
      },
      {
        id: "shwh-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "OQ-DiP-Cuj4",
      },
      {
        id: "shwh-6",
        title: "Patakha Guddi",
        artist: "Nooran Sisters",
        film: "Highway",
        year: 2014,
        duration: 307,
        videoId: "t-p2N4-Y69c",
      },
      {
        id: "shwh-7",
        title: "Zinda",
        artist: "Amit Trivedi",
        film: "Bhaag Milkha Bhaag",
        year: 2013,
        duration: 270,
        videoId: "m5aUe2v9M3Q",
      },
      {
        id: "shwh-8",
        title: "Aazaadiyan",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Udaan",
        year: 2010,
        duration: 310,
        videoId: "l4DlDJdCrc8",
      },
      {
        id: "shwh-9",
        title: "Love You Zindagi",
        artist: "Jasleen Royal",
        film: "Dear Zindagi",
        year: 2016,
        duration: 248,
        videoId: "9B78_tJ589o",
      },
      {
        id: "shwh-10",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "k5Sg1V1n51E",
      },
    ],
  },
];
