export interface Track {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: number;
  duration: number;
  videoId: string;
}

export interface Playlist {
  id: string;
  name: string;
  icon: string;
  description: string;
  time: string;
  tracks: Track[];
}

export const playlists: Playlist[] = [
  {
    id: "subah-ka-sukoon",
    name: "SUBAH KA SUKOON",
    icon: "🌅",
    description: "Fresh, energetic, morning vibes.",
    time: "7 AM – 12 PM",
    tracks: [
      { id: "sksu-1", title: "Khaabon Ke Parinday", artist: "Alyssa Mendonsa, Mohit Chauhan", film: "Zindagi Na Milegi Dobara", year: 2011, duration: 295, videoId: "xZAXVM1rSbk" },
      { id: "sksu-2", title: "Ilahi", artist: "Arijit Singh", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 222, videoId: "4ehgyK5dQfE" },
      { id: "sksu-3", title: "Love You Zindagi", artist: "Jasleen Royal", film: "Dear Zindagi", year: 2016, duration: 248, videoId: "rwn0Zs7ELzc" },
      { id: "sksu-4", title: "Safarnama", artist: "Lucky Ali", film: "Tamasha", year: 2015, duration: 288, videoId: "sOhESxhibAM" },
      { id: "sksu-5", title: "Aashiyan", artist: "Shreya Ghoshal, Nikhil Paul George", film: "Barfi!", year: 2012, duration: 253, videoId: "OuNGySNJjWg" },
      { id: "sksu-6", title: "Patakha Guddi", artist: "Nooran Sisters", film: "Highway", year: 2014, duration: 307, videoId: "rwZDGFuA0xE" }
    ],
  },
  {
    id: "dopahar-ki-dhoop",
    name: "DOPAHAR KI DHOOP",
    icon: "☕",
    description: "Lazy afternoon, mellow, acoustic.",
    time: "12 PM – 4 PM",
    tracks: [
      { id: "dkd-1", title: "Phir Se Ud Chala", artist: "Mohit Chauhan", film: "Rockstar", year: 2011, duration: 283, videoId: "-3gQ6HIkRys" },
      { id: "dkd-2", title: "Kyon", artist: "Papon, Sunidhi Chauhan", film: "Barfi!", year: 2012, duration: 230, videoId: "aQHled_gLxU" },
      { id: "dkd-3", title: "Yun Hi Chala Chal", artist: "Udit Narayan, Hariharan", film: "Swades", year: 2004, duration: 367, videoId: "fXi5ThNAM0w" },
      { id: "dkd-4", title: "Aao Milo Chalo", artist: "Shaan", film: "Jab We Met", year: 2007, duration: 280, videoId: "u7hfwX81bY4" },
      { id: "dkd-5", title: "Iktara", artist: "Kavita Seth", film: "Wake Up Sid", year: 2009, duration: 234, videoId: "ZlOZktsODpA" }
    ],
  },
  {
    id: "chai-aur-chill",
    name: "CHAI AUR CHILL",
    icon: "🌇",
    description: "Relaxing evening transitions.",
    time: "4 PM – 6 PM",
    tracks: [
      { id: "cac-1", title: "Shaam", artist: "Amit Trivedi, Neuman Pinto", film: "Aisha", year: 2010, duration: 265, videoId: "v_hJOCzvABU" },
      { id: "cac-2", title: "Tum Se Hi", artist: "Mohit Chauhan", film: "Jab We Met", year: 2007, duration: 325, videoId: "01HR1uP4kic" },
      { id: "cac-3", title: "Kahin To Hogi Woh", artist: "Rashid Ali, Vasundhara Das", film: "Jaane Tu Ya Jaane Na", year: 2008, duration: 310, videoId: "QGinK1vaK5M" },
      { id: "cac-4", title: "Tu Bin Bataye", artist: "Madhushree, Naresh Iyer", film: "Rang De Basanti", year: 2006, duration: 335, videoId: "jI7FFN4wW5E" },
      { id: "cac-5", title: "Dooba Dooba", artist: "Mohit Chauhan", film: "Silk Route", year: 1998, duration: 282, videoId: "ecPMVO7JuTo" }
    ],
  },
  {
    id: "shaam-ka-sheher",
    name: "SHAAM KA SHEHER",
    icon: "🌆",
    description: "Warm, nostalgic, driving-home vibe.",
    time: "6 PM – 9 PM",
    tracks: [
      {
        id: "sks-1",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "ZlOZktsODpA",
      },
      {
        id: "sks-2",
        title: "Aao Milo Chalo",
        artist: "Shaan, Ustad Sultan Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 280,
        videoId: "u7hfwX81bY4",
      },
      {
        id: "sks-3",
        title: "Khaabon Ke Parinday",
        artist: "Alyssa Mendonsa, Mohit Chauhan",
        film: "Zindagi Na Milegi Dobara",
        year: 2011,
        duration: 295,
        videoId: "xZAXVM1rSbk",
      },
      {
        id: "sks-4",
        title: "Ilahi",
        artist: "Arijit Singh",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 222,
        videoId: "4ehgyK5dQfE",
      },
      {
        id: "sks-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "sOhESxhibAM",
      },
      {
        id: "sks-6",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "fXi5ThNAM0w",
      },
      {
        id: "sks-7",
        title: "Aaj Kal Zindagi",
        artist: "Shankar Mahadevan",
        film: "Wake Up Sid",
        year: 2009,
        duration: 263,
        videoId: "CV9z9Yarbgk",
      },
      {
        id: "sks-8",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "-3gQ6HIkRys",
      },
      {
        id: "sks-9",
        title: "Kyon",
        artist: "Papon, Sunidhi Chauhan",
        film: "Barfi!",
        year: 2012,
        duration: 230,
        videoId: "aQHled_gLxU",
      },
      {
        id: "sks-10",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "DcULR7rk5Js",
      },
    ],
  },
  {
    id: "dil-se",
    name: "DIL SE",
    icon: "❤️",
    description: "Romantic, warm, slightly emotional.",
    time: "9 PM – 11 PM",
    tracks: [
      {
        id: "ds-1",
        title: "Pehla Nasha",
        artist: "Udit Narayan, Sadhana Sargam",
        film: "Jo Jeeta Wohi Sikandar",
        year: 1992,
        duration: 310,
        videoId: "ODu7OyAqK-Q",
      },
      {
        id: "ds-2",
        title: "Gulabi Aankhen",
        artist: "Mohammed Rafi",
        film: "The Train",
        year: 1970,
        duration: 268,
        videoId: "Xsn0QjMN3fM",
      },
      {
        id: "ds-3",
        title: "Aankhon Se Tune Kya Keh Diya",
        artist: "Kumar Sanu",
        film: "Ghulam",
        year: 1998,
        duration: 330,
        videoId: "qEFgYftu29c",
      },
      {
        id: "ds-4",
        title: "Dooba Dooba",
        artist: "Mohit Chauhan",
        film: "Silk Route",
        year: 1998,
        duration: 282,
        videoId: "ecPMVO7JuTo",
      },
      {
        id: "ds-5",
        title: "Tu Bin Bataye",
        artist: "Madhushree, Naresh Iyer",
        film: "Rang De Basanti",
        year: 2006,
        duration: 335,
        videoId: "jI7FFN4wW5E",
      },
      {
        id: "ds-6",
        title: "Zara Zara",
        artist: "Bombay Jayashri",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 327,
        videoId: "6CXI5ZQgo7A",
      },
      {
        id: "ds-7",
        title: "Ajab Si",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 253,
        videoId: "cLPkUggsAsE",
      },
      {
        id: "ds-8",
        title: "Iktara",
        artist: "Kavita Seth",
        film: "Wake Up Sid",
        year: 2009,
        duration: 234,
        videoId: "ZlOZktsODpA",
      },
      {
        id: "ds-9",
        title: "Tum Se Hi",
        artist: "Mohit Chauhan",
        film: "Jab We Met",
        year: 2007,
        duration: 325,
        videoId: "01HR1uP4kic",
      },
      {
        id: "ds-10",
        title: "Kaho Naa Pyaar Hai",
        artist: "Udit Narayan, Alka Yagnik",
        film: "Kaho Naa Pyaar Hai",
        year: 2000,
        duration: 312,
        videoId: "1Nf8eQ9dkGY",
      },
    ],
  },
  {
    id: "raat-abhi-baaki-hai",
    name: "RAAT ABHI BAAKI HAI",
    icon: "🌙",
    description: "Signature late-night playlist.",
    time: "11 PM – 1 AM",
    tracks: [
      {
        id: "rabh-1",
        title: "O Sanam",
        artist: "Lucky Ali",
        film: "",
        year: 1996,
        duration: 306,
        videoId: "qZgTPiuifBo",
      },
      {
        id: "rabh-2",
        title: "Aaoge Jab Tum",
        artist: "Rashid Khan",
        film: "Jab We Met",
        year: 2007,
        duration: 341,
        videoId: "CNZMIhckaA0",
      },
      {
        id: "rabh-3",
        title: "Kahin To Hogi Woh",
        artist: "Rashid Ali, Vasundhara Das",
        film: "Jaane Tu Ya Jaane Na",
        year: 2008,
        duration: 310,
        videoId: "QGinK1vaK5M",
      },
      {
        id: "rabh-4",
        title: "Aankhon Mein Teri",
        artist: "KK",
        film: "Om Shanti Om",
        year: 2007,
        duration: 310,
        videoId: "8tAxzESfBl4",
      },
      {
        id: "rabh-5",
        title: "Tu Jaane Na",
        artist: "Atif Aslam",
        film: "Ajab Prem Ki Ghazab Kahani",
        year: 2009,
        duration: 310,
        videoId: "P8PWN1OmZOA",
      },
      {
        id: "rabh-6",
        title: "Tere Bina",
        artist: "A.R. Rahman, Chinmayi",
        film: "Guru",
        year: 2007,
        duration: 342,
        videoId: "7HKbt19q3Rc",
      },
      {
        id: "rabh-7",
        title: "Kabira",
        artist: "Tochi Raina, Rekha Bhardwaj",
        film: "Yeh Jawaani Hai Deewani",
        year: 2013,
        duration: 260,
        videoId: "jcjOF-MrUs4",
      },
      {
        id: "rabh-8",
        title: "Phir Le Aaya Dil",
        artist: "Arijit Singh",
        film: "Barfi!",
        year: 2012,
        duration: 293,
        videoId: "Z93rAu25KqI",
      },
      {
        id: "rabh-9",
        title: "Shaam",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Aisha",
        year: 2010,
        duration: 265,
        videoId: "v_hJOCzvABU",
      },
      {
        id: "rabh-10",
        title: "Aaj Jaane Ki Zid Na Karo",
        artist: "Farida Khanum",
        film: "",
        year: 1970,
        duration: 427,
        videoId: "C3hOqtRQ9bs",
      },
    ],
  },
  {
    id: "2-baje",
    name: "2 BAJE",
    icon: "🕐",
    description: "For the people who are awake for a reason.",
    time: "1 AM – 3 AM",
    tracks: [
      {
        id: "2b-1",
        title: "Choo Lo",
        artist: "The Local Train",
        film: "",
        year: 2018,
        duration: 304,
        videoId: "sFMRqxCexDk",
      },
      {
        id: "2b-2",
        title: "Aaoge Tum Kabhi",
        artist: "The Local Train",
        film: "",
        year: 2015,
        duration: 317,
        videoId: "hvKaPTmQBA8",
      },
      {
        id: "2b-3",
        title: "Tune Jo Na Kaha",
        artist: "Mohit Chauhan",
        film: "New York",
        year: 2009,
        duration: 303,
        videoId: "01HR1uP4kic",
      },
      {
        id: "2b-4",
        title: "Sach Keh Raha Hai Deewana",
        artist: "KK",
        film: "Rehnaa Hai Terre Dil Mein",
        year: 2001,
        duration: 340,
        videoId: "nya9D8kluE0",
      },
      {
        id: "2b-5",
        title: "Alvida",
        artist: "KK",
        film: "Life In A Metro",
        year: 2007,
        duration: 300,
        videoId: "hM9QDpLHhdw",
      },
      {
        id: "2b-6",
        title: "Tujhe Bhula Diya",
        artist: "Mohit Chauhan, Shekhar, Shruti",
        film: "Anjaana Anjaani",
        year: 2010,
        duration: 326,
        videoId: "NPb9WIzIQsQ",
      },
      {
        id: "2b-7",
        title: "Main Rahoon Ya Na Rahoon",
        artist: "Armaan Malik",
        film: "",
        year: 2015,
        duration: 280,
        videoId: "4WB5y4DAcKE",
      },
      {
        id: "2b-8",
        title: "Phir Mohabbat",
        artist: "Mohd. Irfan, Arijit Singh, Saim",
        film: "Murder 2",
        year: 2011,
        duration: 319,
        videoId: "ZZC9T31knpc",
      },
      {
        id: "2b-9",
        title: "Bhula Dena",
        artist: "Mustafa Zahid",
        film: "Aashiqui 2",
        year: 2013,
        duration: 293,
        videoId: "s0ksvPulHt8",
      },
      {
        id: "2b-10",
        title: "Judaai",
        artist: "Rekha Bhardwaj",
        film: "Badlapur",
        year: 2015,
        duration: 298,
        videoId: "t2VaF0ZX65w",
      },
    ],
  },
  {
    id: "highway-mode",
    name: "HIGHWAY MODE",
    icon: "🚛",
    description: "Truck drivers, night-shift workers, insomniacs.",
    time: "3 AM – 5 AM",
    tracks: [
      {
        id: "hm-1",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1972,
        duration: 289,
        videoId: "DcULR7rk5Js",
      },
      {
        id: "hm-2",
        title: "Zindagi Ek Safar Hai Suhana",
        artist: "Kishore Kumar",
        film: "Andaz",
        year: 1971,
        duration: 261,
        videoId: "mzxHflxI-es",
      },
      {
        id: "hm-3",
        title: "Khaike Paan Banaraswala",
        artist: "Kishore Kumar",
        film: "Don",
        year: 1978,
        duration: 303,
        videoId: "ZphoNQVYNi0",
      },
      {
        id: "hm-4",
        title: "Neele Neele Ambar Par",
        artist: "Kishore Kumar",
        film: "Kalaakaar",
        year: 1983,
        duration: 287,
        videoId: "ThHYiiZTB1Y",
      },
      {
        id: "hm-5",
        title: "O Mere Dil Ke Chain",
        artist: "Kishore Kumar",
        film: "Mere Jeevan Saathi",
        year: 1972,
        duration: 295,
        videoId: "_w14bUcxl1c",
      },
      {
        id: "hm-6",
        title: "Mere Sapno Ki Rani",
        artist: "Kishore Kumar",
        film: "Aradhana",
        year: 1969,
        duration: 269,
        videoId: "Nw7lcCNSYy8",
      },
      {
        id: "hm-7",
        title: "Pal Pal Dil Ke Paas",
        artist: "Kishore Kumar",
        film: "Blackmail",
        year: 1973,
        duration: 287,
        videoId: "f5dw3nafOuo",
      },
      {
        id: "hm-8",
        title: "Aane Wala Pal",
        artist: "Kishore Kumar",
        film: "Gol Maal",
        year: 1979,
        duration: 298,
        videoId: "VE3SaNOJPGI",
      },
      {
        id: "hm-9",
        title: "Ek Ajnabee Haseena Se",
        artist: "Kishore Kumar",
        film: "Ajnabee",
        year: 1974,
        duration: 276,
        videoId: "vS_JXshiu68",
      },
      {
        id: "hm-10",
        title: "Chookar Mere Man Ko",
        artist: "Kishore Kumar",
        film: "Yaarana",
        year: 1981,
        duration: 337,
        videoId: "LF5Lz9zPfIw",
      },
    ],
  },
  {
    id: "subah-hone-wali-hai",
    name: "SUBAH HONE WALI HAI",
    icon: "🌅",
    description: "The emotional transition from night to morning.",
    time: "5 AM – 7 AM",
    tracks: [
      {
        id: "shwh-1",
        title: "Kun Faya Kun",
        artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 469,
        videoId: "T94PHkuydcw",
      },
      {
        id: "shwh-2",
        title: "Arziyan",
        artist: "Javed Ali, Kailash Kher",
        film: "Delhi-6",
        year: 2009,
        duration: 384,
        videoId: "dXdD1_AGBZg",
      },
      {
        id: "shwh-3",
        title: "Phir Se Ud Chala",
        artist: "Mohit Chauhan",
        film: "Rockstar",
        year: 2011,
        duration: 283,
        videoId: "-3gQ6HIkRys",
      },
      {
        id: "shwh-4",
        title: "Aashiyan",
        artist: "Shreya Ghoshal, Nikhil Paul George",
        film: "Barfi!",
        year: 2012,
        duration: 253,
        videoId: "OuNGySNJjWg",
      },
      {
        id: "shwh-5",
        title: "Safarnama",
        artist: "Lucky Ali",
        film: "Tamasha",
        year: 2015,
        duration: 288,
        videoId: "sOhESxhibAM",
      },
      {
        id: "shwh-6",
        title: "Patakha Guddi",
        artist: "Nooran Sisters",
        film: "Highway",
        year: 2014,
        duration: 307,
        videoId: "rwZDGFuA0xE",
      },
      {
        id: "shwh-7",
        title: "Zinda",
        artist: "Amit Trivedi",
        film: "Bhaag Milkha Bhaag",
        year: 2013,
        duration: 270,
        videoId: "K9opdAw3Osk",
      },
      {
        id: "shwh-8",
        title: "Aazaadiyan",
        artist: "Amit Trivedi, Neuman Pinto",
        film: "Udaan",
        year: 2010,
        duration: 310,
        videoId: "ugm2SOScEqA",
      },
      {
        id: "shwh-9",
        title: "Love You Zindagi",
        artist: "Jasleen Royal",
        film: "Dear Zindagi",
        year: 2016,
        duration: 248,
        videoId: "rwn0Zs7ELzc",
      },
      {
        id: "shwh-10",
        title: "Yun Hi Chala Chal",
        artist: "Udit Narayan, Hariharan, Kailash Kher",
        film: "Swades",
        year: 2004,
        duration: 367,
        videoId: "fXi5ThNAM0w",
      },
    ],
  },
];
